# Generated by Django 5.2.5 on 2025-08-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DENTIST', 'Dentista'), ('PATIENT', 'Paciente'), ('ADMIN', 'Administrador')], default='PATIENT', max_length=20),
        ),
    ]
