# Generated by Django 5.2.5 on 2025-08-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DENTIST', 'Dentist'), ('PATIENT', 'Patient')], default='PATIENT', help_text='Rol del usuario dentro del sistema', max_length=20),
        ),
    ]
