# Generated by Django 5.2.5 on 2025-08-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_phone_alter_user_role'),
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
    ]
