# Generated by Django 5.2.5 on 2025-08-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250820_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DENTIST', 'Dentist'), ('PATIENT', 'Patient')], default='PATIENT', help_text='Rol del usuario dentro del sistema', max_length=20),
        ),
    ]
