services:
  db:
    image: mysql:8.4
    container_name: dentyx_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=devpass
      - MYSQL_DATABASE=dentista
      - MYSQL_USER=dentyx
      - MYSQL_PASSWORD=devpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pdevpass --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  dbdata:
