# Generated by Django 5.2.5 on 2025-08-16 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='pay_status_method_idx',
            old_name='payments_pa_status_75d3b1_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='appointments.appointment', verbose_name='Cita'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='MXN', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID externo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('MPAGO', 'MercadoPago')], db_index=True, default='CASH', max_length=12, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del recibo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], db_index=True, default='PENDING', max_length=12, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['appointment', 'created_at'], name='pay_appt_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='pay_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('external_id',), name='uniq_payment_external_id_when_present'),
        ),
    ]
