# Generated by Django 5.2.5 on 2025-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=3, verbose_name='Moneda'),
        ),
    ]
