# Generated by Django 5.2.5 on 2025-08-16 18:49

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Ingresa un número de 10 dígitos (solo números).'), django.core.validators.MinLengthValidator(10)], verbose_name='Teléfono'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patient_name_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='patient_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='patient_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_patient_email_lower'),
        ),
    ]
