# Generated by Django 5.2.5 on 2025-08-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('DONE', 'Atendida')], db_index=True, default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='patients.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service')),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
                'indexes': [models.Index(fields=['service', 'scheduled_at'], name='appointment_service_384ffa_idx')],
                'constraints': [models.UniqueConstraint(fields=('full_name', 'email', 'phone', 'service', 'scheduled_at'), name='uniq_requester_service_datetime')],
            },
        ),
    ]
